---
- name: Add users
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.pwd }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
    state: present
    password_expire_min: 0
  loop: "{{ users }}"

- name: Create .ssh directory for users
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ users }}"

- name: Copy SSH public key to authorized_keys
  ansible.builtin.copy:
    src: "/home/bil/.ssh/id_rsa.pub"
    dest: "/home/{{ item.username }}/.ssh/authorized_keys"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ users }}"
