---
- name: Add users
  user:
    name: "{{ item.username }}"
    password: "{{ item.pwd }}"
    shell: "{{ item.shell }}"
    state: present
  loop: "{{ users }}"

- name: Create .ssh directory for users
  file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0700'
  loop: "{{ users }}"

- name: Copy SSH public key to authorized_keys
  copy:
    src: "/home/bil/.ssh/id_rsa.pub"
    dest: "/home/{{ item.username }}/.ssh/authorized_keys"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0600'
  loop: "{{ users }}"
